api:
  - any: ["frontend/src/ts/ape/**/*", "backend/src/api/**/*"]

assets:
  - any: ["frontend/static/**/*"]
    all: ["!frontend/static/**/*.html"]

backend:
  - any: ["backend/**/*"]

docs:
  - any: ["**/*.md"]

frontend:
  - any: ["frontend/**/*"]

packages:
  - any: ["packages/**/*"]

documentation:
  - any:
      [
        "**/turbo.json",
        "**/tsconfig.json",
        "**/knip.json",
        "**/.prettierrc.json",
        "**/.oxlintrc.json"
      ]
